### ISSUE TITLE
Using mavwp without QGC

### ISSUE THREAD

**Issue by Iko-Git** [ArduPilot/pymavlink#474] opened 2020-11-06 08:28 UTC
Hello,
How can I use mavwp for the following scenario?! (local navigation will be based on importing waypoints from .txt file without relying on QGroundControl or GPS info)
In other words, setting altitude and speed and navigating into pre-specified three points (e.g. on x 5 meters and then on y 3 meters)

**Comment by amilcarlucas** [comment] 2020-11-09 10:34
This is a support question, not a bug. Closing.

Please ask support questions in the ardupilot forum or in the chat.

**Closed by amilcarlucas** 2020-11-09 10:34 UTC
